# Generated by Django 5.1.7 on 2025-06-06 19:44

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_sitecomment_is_approved_tourcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcomment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دیسلایک'),
        ),
        migrations.AddField(
            model_name='tourcomment',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک'),
        ),
        migrations.AddField(
            model_name='tourcomment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز از ۵'),
        ),
        migrations.AddField(
            model_name='tourcomment',
            name='trip_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ سفر'),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='comment',
            field=models.TextField(verbose_name='متن نظر'),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز (از ۵)'),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='sitecomment',
            name='user_role',
            field=models.CharField(choices=[('user', 'کاربر عادی'), ('tour_manager', 'مسئول تور')], editable=False, max_length=20, verbose_name='نقش کاربر در سایت'),
        ),
        migrations.AlterField(
            model_name='tourcomment',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
    ]
