# Generated by Django 5.1.7 on 2025-06-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_tourcomment_dislikes_tourcomment_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'tour comment', 'verbose_name_plural': 'tour comments'},
        ),
    ]
