# Generated by Django 5.1.7 on 2025-06-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_tourcomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecomment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='آیا تأیید شده است؟'),
        ),
    ]
