# Generated by Django 5.1.7 on 2025-06-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_sitecomment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcomment',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
