# Generated by Django 5.1.7 on 2025-05-28 16:48

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('national_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=11)),
                ('payment_status', models.CharField(choices=[('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='paid', max_length=10)),
                ('registration_date', django_jalali.db.models.jDateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='tour.booking')),
            ],
        ),
    ]
