# Generated by Django 5.1.7 on 2025-04-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_attraction_created_at_remove_tour_facilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='built_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
