# Generated by Django 5.1.7 on 2025-06-06 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_attraction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attractions/images/')),
                ('image_type', models.CharField(choices=[('thumbnail', ' 1تصویر کارت'), ('detail', 'تصویر صفحه جزئیات'), ('card2', 'تصویر کارت2')], max_length=20)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.attraction')),
            ],
        ),
    ]
