# Generated by Django 5.2 on 2025-04-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_alter_attraction_built_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='historical_period',
            field=models.CharField(choices=[('Achaemenid', 'هخامنشیان'), ('Ilkhanid', 'ایلخانیان'), ('Parthian', 'اشکانیان'), ('Timurid', 'تیموریان'), ('Sassanid', 'ساسانیان'), ('Safavid', 'صفویان'), ('Seljuk', 'سلجوقیان'), ('Qajar', 'قاجار'), ('Uncertain', 'نامشخص')], default='Uncertain', max_length=20),
        ),
    ]
