# Generated by Django 5.1.7 on 2025-06-06 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_attractionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tours/images/')),
                ('image_type', models.CharField(choices=[('thumbnail', 'تصویر کارت'), ('detail', 'تصویر جزئیات'), ('card2', 'تصویر کارت دوم')], max_length=20)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour.tour')),
            ],
        ),
    ]
