# Generated by Django 5.1.7 on 2025-06-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.CharField(choices=[('featured', 'پربازدید'), ('hidden', 'کمتر شناخته\u200cشده'), ('normal', 'معمولی')], default='normal', max_length=20),
        ),
    ]
