# Generated by Django 5.2 on 2025-04-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_attraction_historical_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='historical_period',
            field=models.CharField(choices=[('Ilamian', 'ایلامیان'), ('Achaemenid', 'هخامنشیان'), ('Ilkhanid', 'ایلخانیان'), ('Parthian', 'اشکانیان'), ('Timurid', 'تیموریان'), ('Sassanid', 'ساسانیان'), ('Safavid', 'صفویان'), ('Seljuk', 'سلجوقیان'), ('Qajar', 'قاجار'), ('Uncertain', 'نامشخص')], default='Uncertain', max_length=20),
        ),
    ]
