# Generated by Django 5.1.7 on 2025-06-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
