# Generated by Django 5.1.7 on 2025-04-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_rename_image_tour_main_image_remove_tour_attractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='attractions',
            field=models.ManyToManyField(related_name='tours', to='tour.attraction'),
        ),
        migrations.AddField(
            model_name='tour',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت حرکت'),
        ),
        migrations.AddField(
            model_name='tour',
            name='return_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت برگشت'),
        ),
    ]
