# Generated by Django 5.1.7 on 2025-04-29 07:35

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tour_attractions_tour_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ بازگشت'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ شروع'),
        ),
    ]
