# Generated by Django 5.1.7 on 2025-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'لطفاً یک ایمیل معتبر وارد کنید.', 'unique': 'این ایمیل قبلاً ثبت شده است.'}, max_length=254, unique=True),
        ),
    ]
