# Generated by Django 5.1.7 on 2025-06-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1125454, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourmanagerprofile',
            name='company_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tourmanagerprofile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tourmanagerprofile',
            name='company_registration_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
