# Generated by Django 5.1.7 on 2025-06-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name_fa',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام فارسی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_fa',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی فارسی'),
        ),
        migrations.AddField(
            model_name='tourmanagerprofile',
            name='first_name_fa',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام فارسی'),
        ),
        migrations.AddField(
            model_name='tourmanagerprofile',
            name='last_name_fa',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی فارسی'),
        ),
    ]
