# Generated by Django 5.2 on 2025-04-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tourmanagerprofile'),
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
    ]
