# Generated by Django 5.1.7 on 2025-06-05 11:37

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tour', '0002_delete_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_price', models.PositiveIntegerField(verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour', verbose_name='تور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('payment_status', models.CharField(choices=[('paid', 'پرداخت شده'), ('unpaid', 'پرداخت نشده')], default='paid', max_length=10, verbose_name='وضعیت پرداخت')),
                ('registration_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='reserve.reservation', verbose_name='رزرو')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نوع اتاق')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('total', models.PositiveIntegerField(verbose_name='تعداد کل اتاق\u200cها')),
                ('remaining', models.PositiveIntegerField(verbose_name='تعداد باقی\u200cمانده')),
                ('price_per_room', models.PositiveIntegerField(verbose_name='قیمت هر اتاق')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='tour.tour', verbose_name='تور')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='تعداد رزرو شده')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_rooms', to='reserve.reservation', verbose_name='رزرو')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.roomtype', verbose_name='نوع اتاق')),
            ],
        ),
    ]
