services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tour_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tour1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static  # اضافه شده
      - ./media:/app/media     # اضافه شده
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: "your-secret-key"
      DEBUG: "false"
      POSTGRES_DB: tour_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tour1234
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
  static_data:    # اضافه شده
  media_data:     # اضافه شده
